sonar.projectKey=takuhii_Unit-Testing-Without-Tests
sonar.organization=takuhii

sonar.sources=src
sonar.tests=tests

sonar.test.inclusions=tests/**/*.test.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8